### PR TITLE
Docs: Update brew installation instructions

### PR DESCRIPTION
**Pull request by adiabatic**

### CODE REVIEW

**Comment by adiabatic** [comment]
I haven't used Mailpit yet, but it was in the New Formulae list when I updated Homebrew just now.

**Comment by axllent** [comment]
That's strange because it's not listed/available on https://formulae.brew.sh/formula/ . Are you 100% sure?

**Comment by axllent** [comment]
Actually I just found https://formulae.brew.sh/formula/mailpit - my guess is it's so new (13 hours) that it's not showing in the search yet. I'll continue to monitor this.

**Comment by adiabatic** [comment]
> That's strange because it's not listed/available on https://formulae.brew.sh/formula/ . Are you 100% sure?

```
> which mailpit
/opt/homebrew/bin/mailpit
```

```
> brew info mailpit
==> mailpit: stable 1.7.1 (bottled)
Web and API based SMTP testing
https://github.com/axllent/mailpit
/opt/homebrew/Cellar/mailpit/1.7.1 (6 files, 18.1MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-07-14 at 16:14:06
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mailpit.rb
License: MIT
==> Dependencies
Build: go ✘, node ✔
==> Analytics
install: 0 (30 days), 0 (90 days), 0 (365 days)
install-on-request: 0 (30 days), 0 (90 days), 0 (365 days)
build-error: 0 (30 days)
```

Yes. Either that, or I'm having the _weirdest dream ever_.

**Comment by axllent** [comment]
It's now appearing in the search, so it must be some cache rebuild thing on the brew website. Looks legit, so now I need to figure out how to deprecate my tap without breaking systems.

**Pull request merged**
