### PR TITLE
:splarkles: Theme toggler

### PR DESCRIPTION
**Pull request by jrmessias**
Add toggler to change theme (light, dark, auto)

### CODE REVIEW

**Review by hizotech — APPROVED** [review]
Good

**Review by hizotech — APPROVED** [review]

**Review by hizotech — APPROVED** [review]

**Comment by axllent** [comment]
This is very nice, thank you! I have a bit of testing to do, and some minor styling changes to fix a few issues with the toggle, but I'll definitely be merging this in.

**Comment by axllent** [comment]
Thanks again for your PR @jrmessias!. I have reworked what you created into a Vue component and shifted the toggle to the bottom left (next to the `About` link) so it does not interfere with the message display. I am aware that the toggle is not visible nor accessible in mobile view (still on my TODO list), but that seemed a more appropriate position to have it. This has just been released in [v1.7.0](https://github.com/axllent/mailpit/releases/tag/v1.7.0).

**Comment by jrmessias** [comment]
Hi @axllent
Thanks for accept my PR, I understand your considerations, thanks for the code review, I always learning. I always programming at night so dark mode is my default :D
Thank you so much.
Best regards.

**Pull request merged**
