### PR TITLE
also push the container image to ghcr.io

### PR DESCRIPTION
**Pull request by shizunge**
Since the codes are hosted on github and workflow is enabled. We can also push the image to ghcr.io.

### CODE REVIEW

**Comment by axllent** [comment]
Thanks. Could you please tell me the following so I understand your reasoning:
1. Why would you limit it to `docker/login-action@v2.1.0` as that won't include minor releases - compared to `docker/login-action@v2` which will always be current within the v2 branch?
2. Is there any advantage of hosting docker images in two places?

**Comment by shizunge** [comment]
1. I copied it from my current project, that is from dependabot I believe.
2. Docker hub imposes a rate limit on free account. If I remember correctly, the rate limit is based on the number of queries to the image's manifest data, meaning that even if you're only checking for new versions of an image and not actually downloading anything, you may still hit the limit.
  To my knowledge, ghcr.io today has no rate limit for free user, which may make it a more attractive option for those who need to make frequent queries to container images.

**Comment by axllent** [comment]
I think you may have misunderstood the free limits, or I have maybe misunderstood your point. Yes Docker Hub does have [download limits](https://docs.docker.com/docker-hub/download-rate-limit/), but that is based on the IP address downloading/pulling the images, not a the number of downloads an image on Docker Hub can have.

> Docker Hub limits the number of Docker image downloads (“pulls”) based on the account type of the user pulling the image. Pull rates limits are based on individual IP address. For anonymous users, the rate limit is set to 100 pulls per 6 hours per IP address. For authenticated users, it's 200 pulls per 6 hour period.

I would argue that the vast majority of all Docker images are hosted on Docker Hub, and those hosted on Docker Hub would likely account for 99% of all image downloads (think: Alpine, Ubuntu, MySQL/Mariadb, PostgreSQL, PHP, Go etc). Users hitting those rate limits would likely be corporate / development agencies with streamlined and very regular CI testing, so would probably already be running with paid Docker accounts as their entire testing infrastructure would be failing (Mailpit would only be a one image in their larger testing).

Whilst I appreciate the thought, I think I'll pass on this for now - unless someone can make a case as to why I should maintain two different Docker registries.

**Comment by shizunge** [comment]
For my use case, if I use all images from docker hub and update all my
selfhost services within 6 hours, I may hit the rate limit. That is why I
prefer an image outside docker hub.

I probably under estimate the cost to  maintain two different Docker
registries. Could you please tell me more, so I can take them into
consideration next
time?

**Comment by axllent** [comment]
That is more-or-less my point - _if_ you moved all your stuff to Docker Hub, you _may_ possibly hit your limit ~ but this isn't what you are doing, so this is not an issue for you, am I correct? I don't know how you are currently using Docker in your infrastructure though, nor how large it is, but this appears to be "fixing" an issue you don't have.

The reason I prefer not to maintain two separate registries is not because it is more difficult to build & push to more than one registry (that's easy and automated). Some of the reasons are as follows: 
- At the moment there is one "source of truth" for the Mailpit Docker images, one option for people to download the official images., no confusion as to which should be used and which are official, especially with the growing number of projects integrating with it.
- One less infrastructure failure point during automated Docker release builds.
-  If someone reports "docker is not working" I know exactly which it is. 
- I can track the number of downloads of the Docker images.
- If a single network is making that many repeated requests to any public Docker registry for the same images, then they are doing it wrong - they should be using [caching proxies](https://docs.docker.com/network/proxy/) (or paying Docker for the service).
- If someone is hitting the download limits, it would be because they are also downloading a list of other images at the same time too, so should all the projects now be expected to also mirror on ghcr.io or elsewhere? Mailpit is just a single image in a much bigger environment. 

So as I said before, _if_ someone can make a good argument for mirroring the images elsewhere (eg: ghcr.io) then I will definitely consider it, but from what I can see now (if I understand it correctly), it should not currently be an issue for anyone.

I hope that makes sense to you?

**Pull request closed without merging**
